research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any relevant information of renowned sources.
  expected_output: >
    A set of relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: analyst

writing_task:
  description: >
    Using the information received, write a report, translating very technical terms into more common language.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A report separated into the most important topics written in web page format, with text and bullet points.
  agent: summarizer
